config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :polls

  root to: "polls#index"

devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, 
           :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', sign_up: 'register'}

resources :polls do 
  member do
    put "like", to: "polls#upvote"
    put "dislike", to: "polls#downvote"
  end
end

end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/poll.rb
class Poll < ActiveRecord::Base

  has_many :comments
  belongs_to :user
  # has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  acts_as_votable
  acts_as_disqusable

  has_attached_file :image, 
:path => ":rails_root/public/system/:attachment/:id/:basename_:style.:extension",
:url => "/system/:attachment/:id/:basename_:style.:extension",
:styles => {
  :thumb    => ['100x100#',  :jpg, :quality => 70],
  :preview  => ['480x480#',  :jpg, :quality => 70],
  :large    => ['600>',      :jpg, :quality => 70],
  :retina   => ['1200>',     :jpg, :quality => 30]
},
:convert_options => {
  :thumb    => '-set colorspace sRGB -strip',
  :preview  => '-set colorspace sRGB -strip',
  :large    => '-set colorspace sRGB -strip',
  :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
}

  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

         has_many :polls
         has_many :comments
         acts_as_voter
         acts_as_disquser :username => :first_name, :email => :email

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
     
    end
  end

    def self.new_with_session(params, session)
      super.tap do |user|
        if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank?
        end
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

# before_filter :configure_permitted_parameters, if: :devise_controller?

#   protected

#   # def configure_permitted_parameters
#   #   devise_parameter_sanitizer.for(:account_update) << :avatar
#   # end


#  def configure_permitted_parameters
#    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password) }
#    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password) }  
#  end

end
  

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]

  def upvote 
  @poll = Poll.find(params[:id])
  @poll.upvote_by current_user
  redirect_to :back
end  

def downvote
  @poll = Poll.find(params[:id])
  @poll.downvote_by current_user
  redirect_to :back
end

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
   
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:title, :positive, :negative, :image)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
 class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pollr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
    <body>

    	<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '794634037307519',
      xfbml      : true,
      version    : 'v2.5'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

		<nav class="navbar navbar-default">
			  <div class="container-fluid">
			    <!-- Brand and toggle get grouped for better mobile display -->
			    <div class="navbar-header">
			      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
			      <%= link_to "PollBanter", root_path, class: "navbar-brand" %>
			    </div>

			    <!-- Collect the nav links, forms, and other content for toggling -->
			    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			     

			      <ul class="nav navbar-nav navbar-right">
			        
			         <ul class="nav navbar-nav">
			        
				<% if user_signed_in? %>
					<li><%= link_to current_user.name, edit_user_registration_path %></li>
					<li><%= link_to "Log Out", destroy_user_session_path, method: :delete%></li>
			
				<% else %>
					<li><%= link_to "Register", new_registration_path(User) %></li>
					<li><%= link_to "Log in",  new_user_session_path %></li>
				<% end %>

				 </ul>

			          </ul>
			        </li>
			      </ul>
			    </div><!-- /.navbar-collapse -->
			  </div><!-- /.container-fluid -->
		</nav>
				     <div class="container-fluid">
				<%= yield %>
			 		</div>
	</body>
</html>

app/views/polls/_form.html.erb
<%= simple_form_for(@poll) do |f| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   
    <%= f.input :title %>
  
  
  
    <%= f.input :positive %>
  
    <%= f.input :negative %>
  
    <%= f.input :image %>

  
    <%= f.button :submit %>
  
<% end %>

app/views/polls/edit.html.erb
<h1>Editing Poll</h1>

<%= render 'form' %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

<p id="notice"><%= notice %></p>

<h1>Listing Polls</h1>

    <div class="row">
      <% @polls.each do |poll| %>
        <div class="col-xs-1 col-md-2"><%= link_to poll.title, poll %>
          <%= link_to(image_tag(poll.image.url(:thumb)), poll) %>        
        </div>
      <% end %>  
    </div>

        






<%= link_to 'New Poll', new_poll_path %>

app/views/polls/new.html.erb
<h1>New Poll</h1>

<%= render 'form' %>

<%= link_to 'Back', polls_path %>

app/views/polls/show.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

<%= disqus_init %>

<p id="notice"><%= notice %></p>


<%= image_tag @poll.image.url(:thumb), class:"test" %>

<button class="hideee">
<%= link_to like_poll_path(@poll), method: :put do %>
  <%= @poll.positive %>
  <%= @poll.get_upvotes.size %>
<% end %>
</button>
<button class="hideee">
<%= link_to dislike_poll_path(@poll), method: :put do %>
  <%= @poll.negative %>
  <%= @poll.get_downvotes.size %>
</button>

<% end %>

 <%= pie_chart [[@poll.positive, @poll.get_upvotes.size], [@poll.negative, @poll.get_downvotes.size]] %> 

 <%= social_share_button_tag(@poll.title) %>

<%- disqus_thread @poll.id %>

<%= link_to 'Edit', edit_poll_path(@poll) %> |
<%= link_to 'Back', polls_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>